# Generated by Django 6.0.5 on 2026-05-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eleicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estudantil", "Estudantil"),
                            ("sindical", "Sindical"),
                            ("associacao", "Associacao"),
                            ("condominio", "Condominio"),
                            ("conselho", "Conselho"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aberta", "Aberta"),
                            ("encerrada", "Encerrada"),
                            ("apurada", "Apurada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("permite_branco", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Eleitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("nome", models.CharField(max_length=150)),
                ("nome_urna", models.CharField(max_length=50)),
                ("partido_ou_chapa", models.CharField(blank=True, max_length=100)),
                ("proposta", models.TextField(blank=True)),
                ("foto_url", models.URLField(blank=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatos",
                        to="urna.eleicao",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleicao", "numero")},
            },
        ),
        migrations.AddField(
            model_name="eleicao",
            name="criada_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eleicoes_criadas",
                to="urna.eleitor",
            ),
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("em_branco", models.BooleanField(default=False)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("comprovante_hash", models.CharField(max_length=64, unique=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="urna.candidato",
                    ),
                ),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votos",
                        to="urna.eleicao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AptidaoEleitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eleitor", models.CharField(max_length=100)),
                ("data_inclusao", models.DateTimeField(auto_now_add=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aptos",
                        to="urna.eleicao",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleitor", "eleicao")},
            },
        ),
        migrations.CreateModel(
            name="RegistroVotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_votacao",
                        to="urna.eleicao",
                    ),
                ),
                (
                    "eleitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_votacao",
                        to="urna.eleitor",
                    ),
                ),
            ],
            options={
                "unique_together": {("eleitor", "eleicao")},
            },
        ),
    ]
